Nebo15/logger_json

.travis.yml
config/.credo.exs
lib/logger_json.ex
lib/logger_json/formatters/google_cloud_logger.ex
test/unit/logger_json/ecto_test.exs
test/unit/logger_json/plug_test.exs
test/unit/logger_json_test.exs

Closes #10 
This PR adds graceful handling of non-serializable metadata coming from OTP crash reports.
Context: https://github.com/elixir-lang/elixir/blob/master/lib/logger/lib/logger.ex#L285

Log crash reason and initial call metadata gracefully

---

README.md
lib/logger_json/plug/metadata_formatters/google_cloud_logger.ex
test/unit/logger_json/plug_test.exs

Adding the request_path allows this value to be indexed
and filtered upon. Although the request_url attribute includes
the request path, the hostname in the request_url may not be a static value which
can make filtering on the request_path portion slow. Including the
request path as it's own top level attribute resolves this problem.
Resolves #32

Add conn.request_path to google_cloud_logger format

---

README.md
lib/logger_json.ex
lib/logger_json/formatter.ex
lib/logger_json/formatter_utils.ex
lib/logger_json/formatters/basic_logger.ex
lib/logger_json/formatters/google_cloud_logger.ex
test/unit/logger_json/ecto_test.exs
test/unit/logger_json/plug_test.exs
test/unit/logger_json_basic_test.exs
test/unit/logger_json_google_test.exs
test/unit/logger_json_test.exs

This PR adds a "basic" log formatter with no GCP specific log entries. In addition, any shared logging functions between the GCP version and the basic version have been extracted out into a separate module.
This PR is still in progress (i.e needs tests and doc updates)...but I just wanted to make sure this is inline with what you had in mind.
Any input is appreciated. Thanks!

Added basic formatter and refactored common functions

---

lib/logger_json/plug/metadata_formatters/google_cloud_logger.ex

Change `node.pid` into `node.vm_pid`.

Fix incorrect field name in module document

---

README.md

The documentation references the `:loggers` repository configuration option, which has been deprecated since Ecto telemetry was introduced in v3.0.0.
This pull request removes the reference to the deprecated option and replaces it with guidance on how to attach the Ecto telemetry handler and use a new `:log` repository configuration option, to prevent duplicate Ecto logging once the telemetry handler is used.

readme_ecto_telemetry

---

lib/logger_json.ex
test/unit/logger_json_google_test.exs

When use Elixir 1.10 and GoogleCloudLogging Formatter, logger_json's millseconds "time" value be overwritten by metadata microseconds "time".
According to the documentation, logger_json be expected "time" value is milliseconds.
So, Made a change to add "time" to ignored_metadata_keys.
Fixed: #49
```
%{"message" => "hello", "metadata" => %{"domain" => ["elixir"], "dynamic_metadata" => 5, "time" => 1596772387300756, "user_id" => 11}, "severity" => "debug", "time" => "2020-08-07T12:53:07.302Z"}
```
```
%{"domain" => ["elixir"], "logging.googleapis.com/sourceLocation" => %{"file" => "/Users/w1mvy/ghq/github.com/Nebo15/logger_json/test/unit/logger_
json_google_test.exs", "function" => "Elixir.LoggerJSONGoogleTest.test logs binary messages/1", "line" => 59}, "message" => "hello", "severity" => …
```

Ignore metadata "time"

---

.travis.yml

💁 These changes update the patch versions of Elixir used in the CI build matrix to the current generally available versions.

Update Elixir versions in CI build matrix

---

lib/logger_json/formatters/basic_logger.ex
lib/logger_json/formatters/google_cloud_logger.ex
test/unit/logger_json_basic_test.exs
test/unit/logger_json_google_test.exs

> the message: this is usually chardata, but in some cases it may contain invalid data. Since the formatting function should never fail, you need to prepare for the message being anything
from : https://hexdocs.pm/logger/Logger.html#module-custom-formatting
This PR fixes a crash when try to log [IO.chardata()](https://hexdocs.pm/elixir/IO.html#module-chardata).
```
Interactive Elixir (1.10.3) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> require Logger
Logger
iex(2)> Logger.debug([?π])
:ok
iex(3)> :gen_event handler LoggerJSON installed in Logger terminating
** (exit) an exception was raised:
** (ArgumentError) argument error
:erlang.iolist_to_binary([960])
(logger_json 4.0.0) lib/logger_json/formatters/basic_logger.ex:19: LoggerJSON.Formatters.BasicLogger.format_event/5 …
```

Use IO.chardata_to_string/1 instead of IO.iodata_to_binary/1

---

lib/logger_json/formatters/basic_logger.ex
lib/logger_json/formatters/google_cloud_logger.ex
lib/logger_json/jason_safe_formatter.ex
test/unit/json_safe_formatter_test.exs
test/unit/logger_json_basic_test.exs
test/unit/logger_json_google_test.exs

This PR adds a new `JasonSafeFormatter` module which is able to recursively walk metadata and make coerce it into Jason.encode! safe. 
I can confirm that this fixes #40 as we have experienced this in production and a few other Logger crashes related to dodgy data ending up in metadata.
We have made some opinionated calls on how to format the data when not compatible but hopefully this is an improvement on the current situation.
The opinionated bits are likely...
- we coerce Structs to Maps if they implement Jason.Encoder
- we attempt to coerce Keyword lists into Maps
- we convert Tuples to lists
- we inspect functions rather than attempting to call them
Credit where credit is due, I used a few commits from [this coingaming fork](https://github.com/coingaming/logger_json) for some pointers …

Add better formatting protections for non-Jason friendly metadata

---

README.md

Elixir auto-detects the applications in your dependencies and you no longer need to explicitly specify `:extra_applications` in `mix.exs` as a result.
https://hexdocs.pm/mix/Mix.Tasks.Compile.App.html

Remove instructions on extra_applications

---

lib/logger_json/formatters/datadog_logger.ex
lib/logger_json/plug/metadata_formatters/datadog_logger.ex
test/unit/logger_json_datadog_test.exs

This adds a `DatadogLogger` and a `Plug` `DatadogLogger`. Copied mostly from the Google version. Field names are from the [Datadog docs](https://docs.datadoghq.com/logs/processing/attributes_naming_convention/#default-standard-attribute-list) and should work out of the box for most people.
Let me know if there are things I missed, or anything you want changed.
Outputs:
```json
{
"domain": ["elixir"],
"logger": {
"thread_name": "#PID<0.510.0>",
"method_name": "Elixir.Appsignal.initialize/0"
},
"message": "AppSignal disabled.",
"syslog": {
"hostname": [10, 10, 100, 100, 100, 100, 100],
"severity": "info",
"timestamp": "2020-12-14T19:15:28.207Z"
}
}
```
```json
{
"domain": ["elixir"],
"logger": {
"thread_name": "#PID<0.712.0>",
"method_name": …
```

add datadog formatters

---

lib/logger_json/plug.ex
lib/logger_json/plug/metadata_formatters/datadog_logger.ex
lib/logger_json/plug/metadata_formatters/elk.ex
lib/logger_json/plug/metadata_formatters/google_cloud_logger.ex
lib/logger_json/plug_utils.ex

I created a `LoggerJSON.PlugUtils` module to match the `LoggerJSON.FormatterUtils` module. I then moved the `get_header/2` function into it, and moved the common (same in all plug formatters) `remote_ip/1` function in it as well.
I updated the `remote_ip/1` function to only return the client IP address if it was sent through a proxy. According to [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For) and our System76 logs, this header can return a list of IP addresses. Datadog and Google Cloud Logger both document this field as a simple string, not a list of them.
Let me know if this module change is too much and I can undo it. As well as any changes you need. 🎊

fix x-forwarded-for returning a list of ip addresses

---

lib/logger_json/formatters/datadog_logger.ex
test/unit/logger_json_datadog_test.exs

Otherwise datadog is unable to link a log entry to the corresponding trace. See https://docs.datadoghq.com/tracing/faq/why-cant-i-see-my-correlated-logs-in-the-trace-id-panel/?tab=jsonlogs : "ensure the name of the logs attribute that contains the trace id is dd.trace_id"

Prefix span_id and trace_id keys with "dd." to connect logs and traces

---

lib/logger_json/formatters/datadog_logger.ex
test/unit/logger_json_datadog_test.exs

`file_name` and `line` are not reserved keywords for `logger` entry. But I think it's the best place to put this information.

Add filename and line number in DatadogLogger formatter

---

lib/logger_json/plug/metadata_formatters/elk.ex
lib/logger_json/plug/metadata_formatters/google_cloud_logger.ex
mix.exs

`System.get_pid/0` is deprecated in flavor of `System.pid/0`. Since we
use this function, we need to bump minimum elixir requirement to be
at least version 1.9.

Change System.get_pid/0 to System.pid/0

---

lib/logger_json.ex
lib/logger_json/formatter.ex
lib/logger_json/formatters/basic_logger.ex
lib/logger_json/formatters/datadog_logger.ex
lib/logger_json/formatters/google_cloud_logger.ex
test/unit/logger_json/ecto_test.exs
test/unit/logger_json/plug_test.exs
test/unit/logger_json_basic_test.exs
test/unit/logger_json_datadog_test.exs
test/unit/logger_json_google_error_reporter_test.exs
test/unit/logger_json_google_test.exs

When logging to Datadog from a kubernetes cluster, the syslog hostname is set to the container hostname. This means Datadog will try to use the container hostname as the actual host name for metrics, traces, etc. Because of this, nothing will link up successfully. Sadly you can't rewrite that or do some sort of pipeline fix for this.
Removing the syslog hostname means that dd-agent will fall back to its native hostname logic. This will pick up the same hostname when running on a regular server (non containerized), and it will pick up the correct (node) host name when running in a container (kubernetes).

feat: allow setting Datadog syslog.hostname attribute

---

lib/logger_json.ex

This was missed when I was converting the keyword list to a map in https://github.com/Nebo15/logger_json/pull/87

Update formatter_opts documentation

---

lib/logger_json/formatters/datadog_logger.ex
test/unit/logger_json_datadog_test.exs

This is to allow Open Telemetry trace ids to be converted into Datadog format so logs and traces can be linked together. Datadog has a [page on how to do this](https://docs.datadoghq.com/tracing/other_telemetry/connect_logs_and_traces/opentelemetry/?tab=go). Most of the code was stollen from the golang example, and then the test values were stollen from known good versions based off that go code. You'll notice that the code is very defensive in case some bad value gets there and starts breaking things. ~I'll also mention that this is probably not the most optimized version. I'm not great with binary pattern matching so improvements welcome.~
Currently this is what would show up out of the box in Datadog with https://github.com/open-telemetry/opentelemetry-erlang setup.
**Note** I'm going …

feat: allow converting otel trace ids to datadog values

---

lib/logger_json.ex

[Logger.compare_levels/2](https://hexdocs.pm/logger/Logger.html#compare_levels/2) triggers [IO.warn/1](https://hexdocs.pm/elixir/IO.html#warn/1) whenever we use it with `:warn` as parameter:
- https://github.com/elixir-lang/elixir/blob/v1.16.1/lib/logger/lib/logger.ex#L625-L630
- https://github.com/elixir-lang/elixir/blob/v1.16.1/lib/logger/lib/logger.ex#L1164-L1167
Sadly, any backend configured for `Logger` will translate `:warning` level to `:warn` for backward compatibility ([ref](https://hexdocs.pm/logger_backends/LoggerBackends.html#module-custom-backends)), which makes the current implementation of this library to always trigger the `IO` warn message for warning logs.
This PR addresses that by converting the log `:warn` level to `:warning` before calling `Logger.compare_levels/2` …

Translate warn to warning for Elixir >= 1.11.0

---

mix.exs

The git tags do not have the `v` prefix so we need to drop it from the `source_ref` for the doc links to work :)

Drop prefix from docs source ref

---

lib/logger_json/formatters/basic.ex

Some log processors can't process JSON logs if they are spread across multiple lines.
I saw the other formatters don't have `pretty` at all so I'm not sure if it's intentional.

Make pretty JSON formatting optional in basic formatter

---

.github/workflows/ci.yml
lib/logger_json.ex
mix.exs

Hi there,
I was just trying to use the latest RC in a project with elixir v1.15 and ran into a bit of a problem. Not sure if you intended to make this compatible with elixir 1.15 but apparently I am not the only one trying to [do this](https://github.com/Nebo15/logger_json/issues/104).

Compatibility with Elixir v1.15

---

README.md
lib/logger_json.ex
lib/logger_json/formatters/elastic.ex
test/logger_json/formatters/elastic_test.exs

Hi again :)
When using the Elastic logger in my work project, I noticed that the logging flow for caught exceptions is not very smooth, as I first have to call `Logger.metadata(crash_reason: e)` (where `e` is my caught exception) to save the error context before every `Logger.warning` or `Logger.error` or the like. Even worse, as a caller and especially someone inexperienced with `Logger`, there's no indication as to the lifetime of whatever is passed to `Logger.metadata`. Will it stay there until the next log, will it be included in every log from that point on? (spoiler alert, it's the latter, so you'd need to manually clear the crash reason in the metadata after the log).
tl;dr: this replaces
```elixir
try do
raise "oops"
rescue
e in RuntimeError -> 
Logger.metadata(crash_reason: e) …
```

fix(elastic): better support for logging raised and caught exceptions and fix formatter crash

---

lib/logger_json/plug.ex

Removes documentation text from `LoggerJSON.Plug` that applies to `LoggerJSON.Ecto`, but not this module.

Fix copy & paste bug in the docs

---

README.md
lib/logger_json.ex
lib/logger_json/formatters/basic.ex
lib/logger_json/formatters/datadog.ex
lib/logger_json/formatters/elastic.ex
lib/logger_json/formatters/google_cloud.ex

The documentation mentions that you can configure the logger like this:
`:logger.update_handler_config(:default, :formatter, {Basic, []})`
However, this will give a dialyzer error, because `:logger.update_handler_config` requires the options to be a map: https://www.erlang.org/doc/apps/kernel/logger.html#update_handler_config/3 and https://www.erlang.org/doc/apps/kernel/logger.html#t:formatter_config/0.
This PR changes the `format/2` callback to supports `opts` that are maps and updates the docs so that users don't get dialyzer errors.

Formatter config can be a map

---

lib/logger_json/formatter/redactor_encoder.ex
test/logger_json/formatter/redactor_encoder_test.exs

Right now dates and times are encoded with the struct encoder which makes the logs be very verbose about dates (I'm using Grafana Loki to view logs and it makes it hard to parse visually):
```elixir
%{level: :info, msg: {:string, "some message"}, meta: %{
datetime: DateTime.utc_now(), 
date: Date.utc_today(), 
time: Time.utc_now
}}
|> LoggerJSON.Formatters.Basic.format(metadata: [:datetime, :date, :time]) 
|> IO.chardata_to_string()
|> Jason.decode! 
|> Jason.encode!(pretty: true) 
|> IO.puts 
```
```elixir
{                                                                                                                                                           
"message": "some message", …
```

Keep native DateTime, Date and Time struct encoding

---

lib/logger_json/plug.ex
test/logger_json/plug_test.exs

Make the return type of `telemetry_logging_handler` conform to its spec.
Currently, if the `if level = level(level, conn)` condition fails, the function returns `nil`, not `:ok` as specified.

Always return :ok even if nothing is logged

---

lib/logger_json.ex
lib/logger_json/formatter.ex
lib/logger_json/formatters/basic.ex
lib/logger_json/formatters/datadog.ex
lib/logger_json/formatters/elastic.ex
lib/logger_json/formatters/google_cloud.ex
test/logger_json/formatters/basic_test.exs
test/logger_json/formatters/datadog_test.exs
test/logger_json/formatters/elastic_test.exs
test/logger_json/formatters/google_cloud_test.exs

Wanted to get a sanity check before moving forward with other formatters to make sure I'm on the right track.
I'm not 100% sure what to do for testing. I basically need to test the behavior of Jason when passing an encoder option which seems clunky and brittle no matter how it gets implemented. At the moment I'm doing a partial regex match on a pretty printed string. Open to other ideas!

`:encoder_opts` formatter option

---

lib/logger_json/formatters/datadog.ex
lib/logger_json/formatters/elastic.ex
test/logger_json/formatters/datadog_test.exs
test/logger_json/formatters/elastic_test.exs

As mentioned in #124 
`duration_us` is not a valid field in the Elastic Common Schema (the [Elastic forum](https://discuss.elastic.co/t/field-for-http-response-times/272742) recommends using [event.duration](https://www.elastic.co/guide/en/ecs/current/ecs-event.html#field-event-duration)) and DataDog recommends using [`duration`](https://docs.datadoghq.com/standard-attributes/?search=duration&product=log+management), so this PR remaps that.

Remap `duration_us` to spec-compliant fields for Elastic and DataDog formatters

---

lib/logger_json/formatters/google_cloud.ex
test/logger_json/formatters/google_cloud_test.exs
test/support/crashing_gen_server.ex

We were running into a situation where errors caused by GenServers terminating were not being formatted because they were a slightly different shape to what was expected in the formatter. This updates the formatter to handle them.
I'm very open to implementing and/or testing this in a different way - any/all feedback appreciated!

Handle Task/GenServer exits correctly in Google formatter

---

lib/logger_json/formatter/redactor_encoder.ex
mix.exs

If Decimal is not included in the main app depending on LoggerJSON, the following line in `LoggerJSON.Formatter.RedactorEncoder` is not included:
```elixir
def encode(%Decimal{} = decimal, _redactors), do: decimal
```

fix: check if Decimal is loaded in encoder

---

README.md

The previous version would crash once you do the first log as `Basic` without aliases is an unknown module.
For setup/configuration docs I think this is better, so people can easily copy & paste it :)
Thanks for `logger_json`!

Reference full module name in config to enable copy & paste

---

lib/logger_json/formatter/redactor_encoder.ex
test/logger_json/formatter/redactor_encoder_test.exs

Hi 👋 
Currently, `RedactorEncoder` can't handle an improper list and would crash a formatter:
```
iex(1)> LoggerJSON.Formatter.RedactorEncoder.encode([1 | 2], [])
** (FunctionClauseError) no function clause matching in Enum."-map/2-lists^map/1-1-"/2
The following arguments were given to Enum."-map/2-lists^map/1-1-"/2:
#Function<3.49609762/1 in LoggerJSON.Formatter.RedactorEncoder.encode/2>
2
(elixir 1.18.2) lib/enum.ex:1714: Enum."-map/2-lists^map/1-1-"/2
(elixir 1.18.2) lib/enum.ex:1714: Enum."-map/2-lists^map/1-1-"/2
iex:1: (file)
```
This PR attempts to fix it. There are probably multiple ways this can be addressed, but I went with `inspect`ing the list after all individual elements were encoded. This way it'll be visible that something isn't right and no data will go unredacted.
Oh, …

Handle improper lists in RedactorEncoder

---

lib/logger_json/formatters/datadog.ex
test/logger_json/formatters/datadog_test.exs

At the moment when `GenServer` exits, the `LoggerJSON.Formatters.Datadog` formatter crashes when trying to encode the message, because it can't handle the chardata.
This PR adds conversion in the `format_crash_reason` that doesn't have it yet and a corresponding test (based on `GoogleCloud` one).

Fix Datadog's formatter crash on GenServer exit

---

README.md
lib/logger_json.ex
lib/logger_json/formatter.ex
lib/logger_json/formatters/basic.ex
lib/logger_json/formatters/datadog.ex
lib/logger_json/formatters/elastic.ex
lib/logger_json/formatters/google_cloud.ex
lib/logger_json/redactors/redact_keys.ex
test/logger_json/ecto_test.exs
test/logger_json/formatters/basic_test.exs
test/logger_json/formatters/datadog_test.exs
test/logger_json/formatters/elastic_test.exs
test/logger_json/formatters/google_cloud_test.exs
test/logger_json/plug_test.exs
test/logger_json_test.exs

👋 
This PR adds a utility function to create formatters. Similar to [`Logger.Formatter.new/1`](https://hexdocs.pm/logger/main/Logger.Formatter.html#new/1)
Some other ideas for this PR:
- duplicate docs for each `new/1` to make it easier to use, right now the users need to know that there is a "Shared options" section in the LoggerJSON moduledoc, and I think people are usually too lazy to look for it :)
- add warnings on invalid options passed to `new/1`
- extra type specs on `new/1`?

add <formatter>.new/1

---

lib/logger_json/formatter/metadata.ex
lib/logger_json/formatter/redactor_encoder.ex
lib/logger_json/formatters/basic.ex
test/logger_json/formatter/metadata_test.exs
test/logger_json/formatters/basic_test.exs

Include file, line and mfa in the basic formatter metadata.
Fixes #137

Include file, line and mfa in basic formatter metadata

---

.github/workflows/ci.yml
README.md
config/test.exs
lib/logger_json.ex
lib/logger_json/formatter.ex
lib/logger_json/formatter/redactor_encoder.ex
lib/logger_json/formatters/basic.ex
lib/logger_json/formatters/datadog.ex
lib/logger_json/formatters/elastic.ex
lib/logger_json/formatters/google_cloud.ex
lib/logger_json/redactor.ex
mix.exs
test/logger_json/formatter/redactor_encoder_test.exs
test/logger_json/formatter_test.exs
test/logger_json/formatters/basic_test.exs
test/logger_json/formatters/datadog_test.exs
test/logger_json/formatters/elastic_test.exs
test/logger_json/formatters/google_cloud_test.exs
test/support/logger_case.ex
test/support/name_struct.ex

This PR preserves the current `Jason` encoder usage while allowing the custom configuration of the [JSON](https://hexdocs.pm/elixir/JSON.html) encoder for Elixir 1.18+.
Both setups are set to be tested by the CI: If the Elixir version is less than 1.18, it will test with `Jason`. Otherwise, it will test with `JSON`.

Allow the usage of JSON for Elixir 1.18+

---

lib/logger_json/formatters/datadog.ex
test/logger_json/formatters/datadog_test.exs

feat: report error.kind and error.stack for non-crash error+ logs

---

lib/logger_json/formatters/basic.ex
test/logger_json/formatters/basic_test.exs

Erlang passes `metadata[:file]` as a charlist, which is passed as is by `Basic` formatter. In this PR I changed `Basic` formatter to output the file as a string.
Resolves #158.

Format `metadata[:file]` as string in `Formatters.Basic`

---

lib/logger_json/formatter.ex

Currently the code snippet is not rendered correctly because of the indentation:
https://hexdocs.pm/logger_json/7.0.3/LoggerJSON.Formatter.html#c:new/1

Add indentation to the code snippet for docs
